name       : kerberos
version    : 1.21.2
release    : 21
source     :
    - https://web.mit.edu/kerberos/dist/krb5/1.21/krb5-1.21.2.tar.gz : 9560941a9d843c0243a71b17a7ac6fe31c7cebb5bce3983db79e52ae7e850491
homepage   : http://web.mit.edu/kerberos/
license    : MIT
component  : system.base
summary    : Kerberos 5 network authentication protocol
description: |
    MIT Kerberos V5 is a free implementation of Kerberos 5. Kerberos is a network authentication protocol. It centralizes the authentication database and uses kerberized applications to work with servers or services that support Kerberos allowing single logins and encrypted communication over internal networks or the Internet.
emul32     : yes
patterns   :
    - devel : [/usr/share/examples, /usr/share/man/man8]
builddeps  :
    - pkgconfig32(com_err)
    - pkgconfig32(openssl)
    # Temporary, remove after openssl 3.1 rebuilds are done
    - openssl-32bit-devel
rundeps    :
    - devel :
        - e2fsprogs-devel
    - 32bit-devel :
        - e2fsprogs-32bit-devel
setup      : |
    cd src
    %configure --disable-rpath \
               --enable-dns-for-realm \
               --with-system-ss \
               --with-system-et
build      : |
    cd src
    %make
install    : |
    cd src
    %make_install
    chmod 0755 $installdir/%libdir%/lib*.so*

    # Stateless
    if [[ -z "${EMUL32BUILD}" ]]; then
        install -D -m 00644 $pkgfiles/krb5.tmpfiles $installdir/%libdir%/tmpfiles.d/krb5.conf
    fi
    rmdir -v $installdir/run/krb5kdc \
             $installdir/run/ \
             $installdir/var/krb5kdc \
             $installdir/var/
