name       : kerberos
version    : 5.1.15.2
release    : 11
source     :
    - https://web.mit.edu/kerberos/dist/krb5/1.15/krb5-1.15.2.tar.gz : 1639e392edf25e3b6cfec2ae68f97eb53e07c2dbe74bfeede0108465d5d1c87e
homepage   : http://web.mit.edu/kerberos/
license    : MIT
component  : security
summary    : Kerberos 5 network authentication protocol
description: |
    MIT Kerberos V5 is a free implementation of Kerberos 5. Kerberos is a network authentication protocol. It centralizes the authentication database and uses kerberized applications to work with servers or services that support Kerberos allowing single logins and encrypted communication over internal networks or the Internet.
emul32     : yes
patterns   :
    - devel : [/usr/share/examples, /usr/share/man/man8]
builddeps  :
    - pkgconfig32(com_err)
    - pkgconfig32(openssl)
setup      : |
    cd src
    %configure \
        --enable-dns-for-realm \
        --with-system-es \
        --with-system-et
build      : |
    make -j1 -C src
install    : |
    %make_install -C src
    chmod 0755 $installdir/%libdir%/lib*.so*
