name        : kerberos
version     : 5.1.14
release     : 7
source      :
    - http://web.mit.edu/kerberos/dist/krb5/1.14/krb5-1.14.tar.gz : cedb07fad8331e3ff2983d26e977a2ddba622f379c2b19bfea85bd695930f9e9
homepage    : http://web.mit.edu/kerberos/
license     : MIT
component   : security
summary     : Kerberos 5 network authentication protocol
description : |
    MIT Kerberos V5 is a free implementation of Kerberos 5. Kerberos is a network authentication protocol. It centralizes the authentication database and uses kerberized applications to work with servers or services that support Kerberos allowing single logins and encrypted communication over internal networks or the Internet.
emul32      : yes
patterns    :
    - devel: [/usr/share/examples, /usr/share/man/man8]
builddeps   :
    - pkgconfig(com_err)
    - pkgconfig32(com_err)
    - pkgconfig(openssl)
    - pkgconfig32(openssl)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    cd $workdir/src
    %configure \
        --enable-dns-for-realm \
        --with-system-es \
        --with-system-et
build      : |
    cd $workdir/src
    make -j1
install    : |
    cd $workdir/src
    %make_install
    chmod 0755 $installdir/%libdir%/lib*.so*
